### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by Anisha7** [galkochris/spaceman#1]
Here's some feedback to further improve your code:
- Try adding some tests for spaceman! You can try creating a sample spaceman gameplay situation by testing just the helpers. Is there a way you could throw errors in your test if certain conditions are not met?
- Try adding more details to your ReadMe! Avoid adding links to google docs, especially ones shared with restricted emails. The project spec is only accessible to Make School staff/students. Instead, summarize it. Add details on what your project is, how to run it, and how to play the game.
- You can also challenge yourself further by creating a _Sinister Spaceman_: _After the user guesses a correct letter, change the mystery word to be a new mystery word that is the same word length and uses the same correctly guessed letters_

**Comment by galkochris** [comment]
Thank you! I appreciate your feedback and thank you for your time!
